# Site settings

title: Andrew Crozier
email: wacrozier@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  The programming blog of Andrew Crozier, a postdoctoral researcher and
  computational modeller.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acroz.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/

#twitter_username: jekyllrb
github_username: acroz

# Build settings
markdown: kramdown
