# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:   acroz
tagline: 'Andrew Crozier'
description: > # this means to ignore newlines until "baseurl:"
  Blog of Andrew Crozier, a postdoctoral researcher and
  computational modeller.
url:         http://acroz.github.io
baseurl:     /
date_format: "%-d %B, %Y"

gems:     [jekyll-paginate]
paginate: 8

github: https://github.com/acroz/
